module.exports = [
	{
		name: "Basic Flow",
		gitUrl: "https://github.com/GeekyAnts/react-native-boilerplate-basic-flow",
		sshUrl: "git@github.com:GeekyAnts/react-native-boilerplate-basic-flow.git",
		slug: "react-native-boilerplate-basic-flow",
		keywords: ["Flow", "Husky"],
		type: "Flow",
	},
	{
		name: "Redux Flow",
		gitUrl: "https://github.com/GeekyAnts/react-native-boilerplate-redux-flow",
		sshUrl: "git@github.com:GeekyAnts/react-native-boilerplate-redux-flow.git",
		slug: "react-native-boilerplate-redux-flow",
		keywords: ["Flow", "Husky", "Redux"],
		type: "Flow",
	},
	{
		name: "MobX Flow",
		gitUrl: "https://github.com/GeekyAnts/react-native-boilerplate-mobx-flow",
		sshUrl: "git@github.com:GeekyAnts/react-native-boilerplate-mobx-flow.git",
		slug: "react-native-boilerplate-mobx-flow",
		keywords: ["Flow", "Husky", "MobX"],
		type: "Flow",
	},
	{
		name: "MobX-State-Tree Flow",
		gitUrl: "https://github.com/GeekyAnts/react-native-boilerplate-mobx-state-tree-flow",
		sshUrl: "git@github.com:GeekyAnts/react-native-boilerplate-mobx-state-tree-flow.git",
		slug: "react-native-boilerplate-mobx-state-tree-flow",
		keywords: ["Flow", "Husky", "MobX-State-Tree"],
		type: "Flow",
	},
	{
		name: "Basic TypeScript",
		gitUrl: "https://github.com/GeekyAnts/react-native-boilerplate-basic-typescript",
		sshUrl: "git@github.com:GeekyAnts/react-native-boilerplate-basic-typescript.git",
		slug: "react-native-boilerplate-basic-typescript",
		keywords: ["TypeScript", "Husky"],
		type: "TypeScript",
	},
	{
		name: "Redux TypeScript",
		gitUrl: "https://github.com/GeekyAnts/react-native-boilerplate-redux-typescript",
		sshUrl: "git@github.com:GeekyAnts/react-native-boilerplate-redux-typescript.git",
		slug: "react-native-boilerplate-redux-typescript",
		keywords: ["TypeScript", "Husky", "Redux"],
		type: "TypeScript",
	},
	{
		name: "MobX TypeScript",
		gitUrl: "https://github.com/GeekyAnts/react-native-boilerplate-mobx-typescript",
		sshUrl: "git@github.com:GeekyAnts/react-native-boilerplate-mobx-typescript.git",
		slug: "react-native-boilerplate-mobx-typescript",
		keywords: ["TypeScript", "Husky", "MobX"],
		type: "TypeScript",
	},
	{
		name: "MobX-State-Tree TypeScript",
		gitUrl: "https://github.com/GeekyAnts/react-native-boilerplate-mobx-state-tree-typescript",
		sshUrl: "git@github.com:GeekyAnts/react-native-boilerplate-mobx-state-tree-typescript.git",
		slug: "react-native-boilerplate-mobx-state-tree-typescript",
		keywords: ["TypeScript", "Husky", "MobX-State-Tree"],
		type: "TypeScript",
	},
];
